name: Deploy Portofolio Naufal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/project-web-acas/project-naufal
            git pull origin main

            cd /home/project-web-acas
            docker compose up -d --build portofolio-naufal